version: '3'
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - app
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
